version: "3.7"

services:
  jupyter:
    image: datasource/algorithmic
    build:
      context: .
    container_name: jupyter
    networks:
      - docker_bda-network
    volumes:
      - ./notebooks:/fs       
    #      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - '8888:8888'
    environment:
      - PASSWORD=datasource
networks:
  docker_bda-network:
    external: true

